### ISSUE TITLE
Did the script stop working? 

### ISSUE THREAD

**Issue by przemyslslaw** [cmprmsd/Overleaf-Image-Helper#7] opened 2023-01-27 23:12 UTC
I've used it for a week or so, but I noticed that it stopped working a few days ago, showing this error in Chrome:

![image](https://user-images.githubusercontent.com/764425/215223193-4a402c16-693b-4230-b330-52de2c11af7a.png)

**Comment by cmprmsd** [comment] 2023-01-28 08:22
Does it work in the classic editor?

**Comment by przemyslslaw** [comment] 2023-01-28 20:24
I've switched to "Source (legacy)" mode, refreshed the browser, and indeed the script works fine now.

**Comment by przemyslslaw** [comment] 2023-01-28 20:25
It doesn't seem to work in "Source" mode, though.

**Comment by cmprmsd** [comment] 2023-01-28 20:33
Yup. Known issue. I'll fix this when the new editor becomes available in the community edition. 

Closing this issue as it's a duplicate of the other open issue(s).

**Closed as completed by cmprmsd** 2023-01-28 20:33 UTC
