### ISSUE TITLE
Script loads within overleaf project, but fails to run because of uncaught TypeError (document.querySelector() is null)

### ISSUE THREAD

**Issue by bencrbcp** [cmprmsd/Overleaf-Image-Helper#10] opened 2023-02-21 18:30 UTC
The @match within the script detects that I'm in an overleaf project and gets enabled, however, I can't seem to be able to use the Ctrl+V image pasting functionality.

I checked the browser console and I got the following error:

![image](https://user-images.githubusercontent.com/48733583/220429081-a3c20bcf-ac8c-497c-9193-ee0a27bf99cb.png)

I'm not super experienced with Javascript so I don't have any ideas for fixes immediately.

**Comment by cmprmsd** [comment] 2023-02-21 18:48
Duplicate of #2

**Comment by cmprmsd** [comment] 2023-02-21 18:50
You can use the classic editor. There the plugin will work. :)

**Comment by bencrbcp** [comment] 2023-02-21 18:54
> You can use the classic editor. There the plugin will work. 

Is this what you mean when by classic editor?:

![image](https://user-images.githubusercontent.com/48733583/220433904-592591a7-5f25-40a8-a972-a32845089f0a.png)

~~If it is, I tried it and it unfortunately can't get it working :/~~

EDIT: JK, it works! Just had to refresh. Thank you so much, this will save me so much tedious image importing!!

**Comment by anirudhakulkarni** [comment] 2023-02-26 14:08
Its not showing Source (legacy) option in overleaf.
![image](https://user-images.githubusercontent.com/29736196/221415554-2be0d27d-73fc-4a3e-b975-8de5fe988b65.png)

**Comment by cmprmsd** [comment] 2023-03-02 17:59
@anirudhakulkarni It seems you use the self hosted version. You can use the plugin without any problems as the editor has not been replaced there yet.

**Comment by anirudhakulkarni** [comment] 2023-03-03 11:19
No its overleaf.com only

**Comment by cmprmsd** [comment] 2023-03-03 11:22
Maybe they do some country depending stuff. However, the editor for me and the other users does show source, legacy and rich text. 
I don't know why it is not visible for you. 

Maybe you'll have to opt-in into some beta.

**Comment by Natithan** [comment] 2023-05-01 12:13
Hey! Big fan of the idea :) but it also doesn't work for me at the moment.

It seems like the legacy is definitely retired since 24 apr 2023? https://www.overleaf.com/blog/were-retiring-our-legacy-source-editor

**Comment by cmprmsd** [comment] 2023-05-01 12:45
Yup I also read the message and contacted Overleaf for some technical details. Haven't had the time to fix it yet as we bought a house recently.

Here's the response that should help if anyone is interested: 

```
Thanks for getting in touch and for your work on this helpful script. This change has indeed had an impact on some extensions and scripts, unfortunately.

While none of this is officially supported, here are the best recommendations I know of at the moment.
> Current project name

There is a meta tag, <meta name="ol-projectName" content="Test">, with the project name.

> root folder of the project and

_ide.fileTreeManager.findEntityByPath('') should still work, at least for now.

> making the selection (cursor move) in the editor via JS

If you look at
console.log(window.UNSTABLE_editorHelp)
there are some pointers for how to hook into the CodeMirror 6 editor.

I hope that helps!

Best,
John

—
Dr John Lees-Miller
```

I hope to find the time soon, but do appreciate any help/ pull request. :)

**Comment by enteryournamehere** [comment] 2023-05-04 15:19
This adaptation of your script does work with the new editor: https://greasyfork.org/en/scripts/461190-overleaf-paste-images-from-clipboard

**Comment by cmprmsd** [comment] 2023-06-16 07:38
@enteryournamehere 
Thanks! Would you mind if I borrow some code back from your adaption and merge it into the main tree of this project?

I think Overleaf now has the new editor integrated also into the on-prem community version.

**Comment by enteryournamehere** [comment] 2023-06-16 07:45
I'm not the author of the version I linked, I just found it, but it's GPL v3 licensed (it's gotta be, as yours is too) so you can definitely do that if you just follow those terms (state changes, include attribution, [etc](https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3))

**Comment by cmprmsd** [comment] 2023-06-16 07:57
Thanks for the clarification :+1: 
Oh right, lucky me! That's one of the few projects where I started to include a LICENSE. :eyes: 

Thanks @BLumbye for your work.

**Comment by cmprmsd** [comment] 2023-08-11 03:21
Just merged an update PR by @ColinRoitt for Code Mirror 6. So the current version of Overleaf should now be fully supported!

**Closed as completed by cmprmsd** 2023-08-11 03:21 UTC
