### ISSUE TITLE
Only works for Legacy

### ISSUE THREAD

**Issue by s204475** [cmprmsd/Overleaf-Image-Helper#8] opened 2023-02-01 16:26 UTC
Sadly it does not work in normal Source mode, but only in Source (legacy) mode.
![image](https://user-images.githubusercontent.com/76941623/216102459-ca695483-08f1-4dbf-95a7-2dc1c780c8a2.png)

**Comment by cmprmsd** [comment] 2023-02-01 18:07
Duplicate of the other issue(s)

**Closed as completed by cmprmsd** 2023-02-01 18:07 UTC
